### ISSUE TITLE
V1 Todo List

### ISSUE THREAD

**Issue by dannyfreeman** [clojure-emacs/clojure-ts-mode#1]
This is what I have left to do before this is ready for general use:

- [x] Font Locking
- [x] [Fixed](https://tonsky.me/blog/clojurefmt/) Indentation
- [x] Prompt for user to auto install clojure grammar if not found
    - Download and compile for user
    - OR Download precompiled binaries
- [x] List on melpa
    - PR Open: https://github.com/melpa/melpa/pull/8545
- [x] imenu support
    - [x] ns
    - [x] defn/defmethod
    - [x] def/defonce
    - [x] defmacro
    - [x] defprotocol/definterface/defmulti
    - [x] deftype/defrecrod/defstruct
- [X] CI/CD
    - Linting 
    - Tests (will come later, not sure how exactly to write them yet)
    - ~Build grammar binaries (perhaps this is best done in tree-sitter-clojure)~ no need to build binaries, emacs can do this now.
- [x] which-function-mode support
- [x] Add clojure-ts-mode to eglot, lsp-mode
    - Patch submitted for eglot https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62449 
        - On emacs master branch, probably won't be part of Emacs 29.
        - Can also be managed as part of user config, or installed from ELPA eglot, separate from Emacs
    - PR submitted for lsp-mode https://github.com/emacs-lsp/lsp-mode/pull/4002

This issue is for me to keep track of what needs to be done, not for gathering feedback. Anyone should feel free to open a separate issue if they have a question, bug, request, etc.
